[build]
builder = "NIXPACKS"
buildCommand = "python -m pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn config.wsgi:application"
healthcheckPath = "/admin/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
