[build]
builder = "NIXPACKS"

[deploy]
startCommand = "sh -c 'python manage.py migrate && python manage.py collectstatic --noinput && gunicorn config.wsgi:application'"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.rules]]
plan = "starter"
