# Generated by Django 5.0.1 on 2025-05-10 18:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Boshlanish sanasi")),
                ("end_date", models.DateField(verbose_name="Tugash sanasi")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("kutilmoqda", "Kutilmoqda"),
                            ("qabul_qilindi", "Qabul qilindi"),
                            ("rad_etildi", "Rad etildi"),
                        ],
                        db_index=True,
                        default="kutilmoqda",
                        max_length=15,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Kunlik narx * Kunlar soni",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Umumiy narx",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Buyurtma",
                "verbose_name_plural": "Buyurtmalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Avtomobil brendining nomi",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Brend",
                "verbose_name_plural": "Brendlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100, verbose_name="Model")),
                (
                    "year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2026),
                        ],
                        verbose_name="Ishlab chiqarilgan yil",
                    ),
                ),
                (
                    "seats",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(50),
                        ],
                        verbose_name="O'rindiqlar soni",
                    ),
                ),
                ("color", models.CharField(max_length=30, verbose_name="Rangi")),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Kunlik ijara narxi",
                    ),
                ),
                (
                    "total_quantity",
                    models.PositiveIntegerField(verbose_name="Umumiy soni"),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[("avtomat", "Avtomat"), ("mexanik", "Mexanik")],
                        default="avtomat",
                        max_length=10,
                        verbose_name="Transmissiya",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="car_photos/%Y/%m/",
                        verbose_name="Rasm",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Avtomobil",
                "verbose_name_plural": "Avtomobillar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Boshlanish sanasi")),
                ("end_date", models.DateField(verbose_name="Tugash sanasi")),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Umumiy narx",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("faol", "Faol"),
                            ("yakunlangan", "Yakunlangan"),
                            ("bekor_qilingan", "Bekor qilingan"),
                        ],
                        default="faol",
                        max_length=15,
                        verbose_name="Holat",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shartnoma",
                "verbose_name_plural": "Shartnomalar",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="To'lov summasi",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Summa",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("kutilmoqda", "Kutilmoqda"),
                            ("tugallangan", "Tugallangan"),
                            ("xatolik", "Xatolik"),
                        ],
                        db_index=True,
                        default="kutilmoqda",
                        max_length=15,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("uzcard", "UzCard"),
                            ("humo", "Humo"),
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                        ],
                        max_length=20,
                        verbose_name="Karta turi",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        help_text="16 xonali karta raqami",
                        max_length=16,
                        verbose_name="Karta raqami",
                    ),
                ),
                (
                    "card_expire",
                    models.CharField(
                        help_text="Format: MM/YY",
                        max_length=5,
                        verbose_name="Amal qilish muddati",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "To'lov",
                "verbose_name_plural": "To'lovlar",
                "ordering": ["-created_at"],
            },
        ),
    ]
